### ISSUE TITLE
Demo link

### ISSUE THREAD

**Issue by bcalik** [ennorehling/jump-n-bump#1]
Hello,

Is there any working demo link? Thank you.

**Comment by ennorehling** [comment]
There isn't at this time (I stopped paying for that domain), but should be easy to set up again. I'll try to get it up and update the README sometime this week.

**Comment by ennorehling** [comment]
This was easy. Just downloaded the thing onto another web server, and it still works (it's been years since I looked at it): http://www.eressea.kn-bremen.de/jump-n-bump/jnb.html
